chore(website): upgrades ESLint v9
markuplint/markuplint pull request #2001
Opened 2024-08-15 06:27 UTC by YusukeHirao

- Remove `.eslintrc` from `website` directory
- Merge config for `website` to the root `eslint.config.js`

The merge was necessary because Lint Staged doesn’t support running Lint in subdirectories.

2024-08-15 12:52 UTC, YusukeHirao commented
@kagankan 

変更の同意と確認おねがいします。

2024-08-16 09:02 UTC, kagankan commented
@YusukeHirao 
ありがとうございます！
おそらく問題ないと思うのですが、Flat Configについて無知ゆえ、これから概要を把握したうえで確認しますので少しお時間いただきます

2024-08-16 17:01 UTC, kagankan requested changes
設定ファイルをルートに移動すること自体は問題ないのですが、従来の設定をできるだけそのまま移行したく、コメントしました！

2024-08-16 17:01 UTC, kagankan commented on eslint.config.js
>Remove plugins (don't support v9):
>eslint-plugin-react-hooks
>eslint-plugin-import

`@eslint/compat` を使うことでFlat Config非対応のプラグインも利用できるので、これらのプラグインも削除せずに移行できないでしょうか？
参考: https://github.com/t3-oss/create-t3-turbo/issues/984#issuecomment-2210934687

2024-08-16 17:01 UTC, kagankan commented on eslint.config.js
> +const dir = path.resolve(__dirname, 'website');
（細かいことですが）
命名が抽象的なため、websiteのものであるということを示す命名がよさそうです

```suggestion
const websiteDir = path.resolve(__dirname, 'website');
```

2024-08-16 17:01 UTC, kagankan commented on eslint.config.js
> +		files: ['**/*.tsx'],
`website/.eslintrc` にあった設定（＝website配下のみに適用される）であることを考えると、website配下に制限するほうがよさそうですがいかがでしょう？

```suggestion
		files: ['website/**/*.tsx'],
```

2024-08-16 17:01 UTC, kagankan commented on eslint.config.js
> +		files: ['*.js', '**/*.js'],
こちらも

```suggestion
		files: ['website/*.js', 'website/**/*.js'],
```

2024-08-18 11:23 UTC, YusukeHirao commented on eslint.config.js
なんと…そんなことが…！

やってみます。ありがとうございます。

2024-08-18 11:26 UTC, YusukeHirao commented on eslint.config.js
> +		files: ['**/*.tsx'],
Globの形式かルート計算がうまくいかないのか、このパスだと上手くいかないようでした。
よかったらかがんさんも試してみてもらえませんか？

2024-08-18 15:22 UTC, kagankan commented on eslint.config.js
> +		files: ['**/*.tsx'],
おや、そうなんですね
ちょっと確認します

2024-08-18 15:24 UTC, YusukeHirao commented on eslint.config.js
対応できました。ありがとうございます。

（が、importは開発元も未対応としているので、部分適応です）

2024-08-18 15:24 UTC, YusukeHirao commented on eslint.config.js
> +		files: ['*.js', '**/*.js'],
こっちは、絶対パスにすることで対応できました（なぜ…）

2024-08-18 15:55 UTC, kagankan commented on eslint.config.js
> +		files: ['**/*.tsx'],
`files: ['website/**/*.tsx'],`  と ``files: [`${websiteDir}/**/*.tsx`],`` をそれぞれ試して `npx eslint` を実行してみました。
自分の環境だと `files: ['website/**/*.tsx'],`  でルールが適用されました（想定通り）
 ``files: [`${websiteDir}/**/*.tsx`],`` だとルールが適用されなくなってしまいました 🤔 
そのため、 ``files: [`${websiteDir}/*.js`, `${websiteDir}/**/*.js`],`` に対する `'unicorn/prefer-module': 0,` などは適用されておらずエラーとして検出されてしまいます。

自分の環境はWindowsなのでもしかしたらその影響もあるかもしれませんが、
公式のドキュメントを見ても相対パスで書いているので、本来相対パスで動作するのが正しい気がします…！

>files: ["src/**/*.js"],
https://eslint.org/docs/latest/use/configure/configuration-files#excluding-files-with-ignores

2025-03-09 09:29 UTC, closed without merging