Website improvement with Docusaurus
markuplint/markuplint pull request #538
Opened 2022-10-30 09:08 UTC by kagankan

（日本語で失礼します）

前にコメントしてから時間を空けてしまいすみません……！
#461 の改善を含め、サイト全体を使いやすいものにするため、
サイトの実装をNext.jsから[Docusaurus](https://docusaurus.io/)に置き換えるPRを作成しました。

## 主な目的

- サイトを使いやすくしたい
- モバイル表示を最適化したい
- 上記の機能を、少ない管理コストで実現できるようにしたい

## このPRの方針

基本的に、現行サイトの機能・要素はそのまま引き継ぎ、Docusaurusに載せ替えることのみを中心としました。
ただし、フォルダ構成などはDocusaurusのデフォルトに合わせていくのがわかりやすいと判断して変更しています。

## Docusaurusへの変更にあたり追加された機能

- ドキュメントページのナビゲーション
  - 右カラムのページ内目次機能 
  - 左カラムのサイドバー
  - パンくずリスト
- ファビコン
  - ロゴがリニューアルされたら別途更新する想定です
- ドキュメントページの編集リンク

## 変更した部分
- リンクをヘッダーにまとめるため、github, twitterをヘッダーに移動
  - Docusarusのサイトを参考に作成
- markdown frontmatterで指定していた next / backを削除
  - sidebar.jsで順番を指定することでナビゲーションが生成されるため
- アンカーリンクのidを固定
  - https://docusaurus.io/docs/markdown-features/toc#heading-ids
- twitter:title, twitter:imageの指定は省略した場合og:*にフォールバックされるため省略
  - 二重管理を避けたいため
  - 参考: https://developer.twitter.com/ja/docs/tweets/optimize-with-cards/guides/getting-started

## 今回使用しなかった機能の補足

- コンポーネントの調整が可能
  - https://docusaurus.io/docs/swizzling
- 共通部分の翻訳は管理コスト低減のためデフォルトを使用しているが、個別指定も可能
  - https://docusaurus.io/docs/i18n/tutorial#translate-plugin-data
- バージョン別のドキュメント管理も可能
  - https://docusaurus.io/docs/versioning

## ご相談

### GitHub pages deployment config

GitHub pagesでデプロイするための機能が用意されているようなのですが使用しますでしょうか？
https://docusaurus.io/docs/deployment#deploying-to-github-pages
使用する場合は `docusaurus.config.js` の `organizationName` `projectName` を設定するようです（コメントアウトで残しています）。
不要な場合は設定の記述削除で問題ありません。

### 検索機能

検索機能を追加する場合、Algolia DocSearchを使うのがいいようです。
https://docusaurus.io/docs/search#using-algolia-docsearch
使用には [サイトの所有者からの申請が必要](https://docsearch.algolia.com/docs/who-can-apply/)なため、
もし追加を検討頂ける場合、申請していただきたいです。
https://docsearch.algolia.com/apply/

確認箇所多くて恐縮ですが、どうぞよろしくお願いいたします！

2022-10-30 09:15 UTC, kagankan commented
すみません、ブランチの同期方法を間違えたようで、
以前workflowの修正をしたときにテストしていたコミットが含まれてしまっています… 🙇‍♂️
e669194のマージコミット以前のコミットは今回のPRには関係ありません。
不都合ありそうであればブランチ作り直します。

2022-10-31 03:16 UTC, YusukeHirao commented
@kagankan 

めちゃくちゃ助かります！！これ、求めてたやつです！！
これ、採用させてください！

いくつか機能できていない箇所がありそうなので、調整可能ですか？

- パンくずがネスト状態になっていない（ `http://localhost:3000/configuration/regex-selector-sample/` など）
- 日本語のページとナビゲーションが機能、生成されていない…？
  - i18n設計は効率的にやりたいので、改めて相談したいです。

> GitHub pages deployment config

現状Netlifyを使っているので、今のところ不都合がなければここまま未使用でいきたいと思います。

> 検索機能

Algolia申請しておきます！

---

ところで、かがんさん、折角ここまでやっていただけたので、ウェブサイト中心にMaintainerになってもらえませんか？

2022-11-01 15:11 UTC, kagankan commented
@YusukeHirao 

さっそく確認ありがとうございます！

>めちゃくちゃ助かります！！これ、求めてたやつです！！
>これ、採用させてください！

喜んでいただけてよかったです！！ 🙌

>パンくずがネスト状態になっていない（ http://localhost:3000/configuration/regex-selector-sample/ など）
>日本語のページとナビゲーションが機能、生成されていない…？

おおっと失礼しました。追って確認します！
（祝日か土日までには…！）

>現状Netlifyを使っているので、今のところ不都合がなければここまま未使用でいきたいと思います。

OKです！
（デプロイ周りの知識があるわけではなく、一応の確認でした）
コメントアウトしてある設定記述は削除しておきます。

>Algolia申請しておきます！

ありがとうございます！！

>ところで、かがんさん、折角ここまでやっていただけたので、ウェブサイト中心にMaintainerになってもらえませんか？

❗❗
どれだけ貢献できるかわからないですが、自分で良ければお手伝いさせていただきます！ 🙌

2022-11-02 13:11 UTC, YusukeHirao commented
@kagankan 

ありがとうございます！Maintainerに招待します！

Algoliaは現在サポートから連絡が来たので、確認と受理待ちです。

2022-11-03 19:05 UTC, kagankan commented
@YusukeHirao 
Maintainer (Collaborator) の招待ありがとうございました！　参加させていただきました。
どうぞよろしくお願いします！ 🙏

---

>パンくずがネスト状態になっていない

/configuration/regex-selector-sample/ についてはネストに修正しました。
/getting-started/ 他のページについては、ヘッダーのラベルをこのページにしているものの、URLがネストになっていないことも鑑み、それぞれ並列なページと判断してそのままにしています。

>日本語のページとナビゲーションが機能、生成されていない…？

これに関しては、翻訳版を用意していないことによる問題で、生成自体は問題ない認識です。
現状、翻訳がないページ（個別ルールのページ以外）は英語版をフォールバックとして使用しています。
個別ルールのページ(/ja/rules/attr-duplication/ など)については日本語ページを生成しています。
ナビゲーションの翻訳も同様に、ページのタイトルから取得しているため翻訳されていない状態です。

日本語翻訳の追加作業は別途対応として、一旦このPRでは載せ替えのみに絞りたいと考えています（コンテンツの話に踏み込むと範囲が広がりすぎてしまいそうなので…😖）。
#508 で進めていただいてるのを拝見したので、これらを反映するPRを別途立てたいと思います。

このブランチでの対応として、以下修正しています。
- 翻訳のないページに「このページはまだ翻訳が用意されていないため、英語版を表示しています。」の注釈文言を表示する機能を追加
- 編集リンクのURL(editUrl)が、フォールバックとして英語ページを表示している場合に正しくなかったので修正

---

ちなみに、editUrlをdevブランチのリンクに設定しているのは正しいでしょうか？
現在のデフォルトブランチがdevだったのでdevにしていますが、mainではなくて問題ないでしょうか。
dev と mainの使い分けなどあれば知りたいです！

2022-11-04 07:44 UTC, YusukeHirao requested changes

2022-11-04 07:44 UTC, YusukeHirao commented on website/package.json
> +    "site:start:ja": "yarn site:prebuild; docusaurus start --locale ja",
@kagankan 今後言語を増やすことを考えると、素直に

```sh
yarn site:start --locale ja
```

で指定してもらうのでも、問題ないと思います。
READMEにそれが記載されているとなお良いかと（現時点で必ず必要とは言わないです）。

2022-11-04 07:47 UTC, YusukeHirao commented
@kagankan 

> 翻訳のないページに「このページはまだ翻訳が用意されていないため、英語版を表示しています。」の注釈文言を表示する機能を追加
> 編集リンクのURL(editUrl)が、フォールバックとして英語ページを表示している場合に正しくなかったので修正

ありがとうございます！

> ちなみに、editUrlをdevブランチのリンクに設定しているのは正しいでしょうか？
> 現在のデフォルトブランチがdevだったのでdevにしていますが、mainではなくて問題ないでしょうか。
dev と mainの使い分けなどあれば知りたいです！

PR先のデフォルトを`dev`にしておきたかったので、こうなってます。
（もしかしたら設定でできるけど、やり方を知らないだけな気がします…）

なので、`main`にしてもらってOKです。
Netlifyのデプロイは`main`ブランチになっていますので。

2022-11-04 07:48 UTC, YusukeHirao commented
@kagankan 

あと、今後のサイトの更新に対してレビュアーになってもらいたいので
https://github.com/markuplint/markuplint/blob/dev/.github/CODEOWNERS
への追加もお願いします。

2022-11-08 18:35 UTC, kagankan commented on website/package.json
> +    "site:start:ja": "yarn site:prebuild; docusaurus start --locale ja",
@YusukeHirao 
たしかにそうですね！
`site:start:ja` はpackage.jsonからは削除し、READMEに記載しました。

ちなみに、ESLintのウェブサイトリポジトリも同様に、言語別のローカルサーバーは手動でコマンド入力する形でした。
https://github.com/eslint/eslint.org

2022-11-08 18:39 UTC, kagankan commented
@YusukeHirao 
>PR先のデフォルトをdevにしておきたかったので、こうなってます。

なるほどです
たしかに軽く調べた感じだと、PR先の規定のブランチはデフォルトブランチと同一になるみたいなので、PR先をdevにしようとするなら仕方なさそうですね…。
editUrlはmainに変更しました！

CODEOWNERSも追加済みです！

ご確認お願いします。

2022-11-20 08:13 UTC, YusukeHirao commented
@kagankan 

ごめんなさい、マージ先を `v3` に変更しました。
コンフリクトしているので対応お願いできますか？
ちなみに、`v3`にマージされると https://next.markuplint.dev/ に自動でデプロイされます。

2022-11-20 08:13 UTC, YusukeHirao commented on website/package.json
> +    "site:start:ja": "yarn site:prebuild; docusaurus start --locale ja",
ありがとうございます！

2022-11-23 05:24 UTC, kagankan commented
@YusukeHirao 

コンフリクト修正しました！
また、v3ブランチになるため、editUrlをv3のリンクに変更しています。
（mainブランチになるときにはmainに変更しようと思います）

2022-11-24 01:00 UTC, YusukeHirao commented
@kagankan 
ありがとうございます！

2022-11-24 01:06 UTC, YusukeHirao approved these changes

2022-11-24 01:06 UTC, merged

2022-11-24 18:04 UTC, kagankan commented
@YusukeHirao 

マージありがとうございます！
デプロイも確認できました 🎉
https://next.markuplint.dev/

そしてすっかり確認を忘れていたのですが、Algoliaの申請についてその後進展ありましたでしょうか？
おそらく `appId`, `apiKey`, `indexName` の3つがあればサイトに設定できるものと思っています。
もしこれらすでにありましたら教えてください。設定しておきます！

2022-11-25 03:18 UTC, YusukeHirao commented
@kagankan 

Algolia取得できました。Issueにしました。 #573
よろしくお願いします！